services:
- name: service1
  strategy: WeightedRoundRobin
  matcher: "/"
  replicas:
  - url: http://127.0.0.1:8081
    metaData:  # Use metaData instead of metadata
      weight: 10
  - url: http://127.0.0.1:8082
    metaData:  # Use metaData instead of metadata
      weight: 5
