services:
  - name: service1
    strategy: WeightedRoundRobin
    matcher: "/"
    replicas:
      - url: http://127.0.0.1:8081
        metaData:
          weight: 10
      - url: http://127.0.0.1:8082
        metaData:
          weight: 5
      - url: http://127.0.0.1:8083
        metaData:
          weight: 7
      - url: http://127.0.0.1:8084
        metaData:
          weight: 3
      - url: http://127.0.0.1:8085
        metaData:
          weight: 6
      - url: http://127.0.0.1:8086
        metaData:
          weight: 4
      - url: http://127.0.0.1:8087
        metaData:
          weight: 8
      - url: http://127.0.0.1:8088
        metaData:
          weight: 2
      - url: http://127.0.0.1:8089
        metaData:
          weight: 9
      - url: http://127.0.0.1:8090
        metaData:
          weight: 1
      - url: http://127.0.0.1:8091
        metaData:
          weight: 10
      - url: http://127.0.0.1:8092
        metaData:
          weight: 5
      - url: http://127.0.0.1:8093
        metaData:
          weight: 7
      - url: http://127.0.0.1:8094
        metaData:
          weight: 3
      - url: http://127.0.0.1:8095
        metaData:
          weight: 6
      - url: http://127.0.0.1:8096
        metaData:
          weight: 4
      - url: http://127.0.0.1:8097
        metaData:
          weight: 8
      - url: http://127.0.0.1:8098
        metaData:
          weight: 2
      - url: http://127.0.0.1:8099
        metaData:
          weight: 9
      - url: http://127.0.0.1:8100
        metaData:
          weight: 1
      - url: http://127.0.0.1:8101
        metaData:
          weight: 10
      - url: http://127.0.0.1:8102
        metaData:
          weight: 5
      - url: http://127.0.0.1:8103
        metaData:
          weight: 7
      - url: http://127.0.0.1:8104
        metaData:
          weight: 3
      - url: http://127.0.0.1:8105
        metaData:
          weight: 6
      - url: http://127.0.0.1:8106
        metaData:
          weight: 4
      - url: http://127.0.0.1:8107
        metaData:
          weight: 8
      - url: http://127.0.0.1:8108
        metaData:
          weight: 2
      - url: http://127.0.0.1:8109
        metaData:
          weight: 9
      - url: http://127.0.0.1:8110
        metaData:
          weight: 1
      - url: http://127.0.0.1:8111
        metaData:
          weight: 10
      - url: http://127.0.0.1:8112
        metaData:
          weight: 5
      - url: http://127.0.0.1:8113
        metaData:
          weight: 7
      - url: http://127.0.0.1:8114
        metaData:
          weight: 3
      - url: http://127.0.0.1:8115
        metaData:
          weight: 6
      - url: http://127.0.0.1:8116
        metaData:
          weight: 4
      - url: http://127.0.0.1:8117
        metaData:
          weight: 8
      - url: http://127.0.0.1:8118
        metaData:
          weight: 2
      - url: http://127.0.0.1:8119
        metaData:
          weight: 9
      - url: http://127.0.0.1:8120
        metaData:
          weight: 1
      - url: http://127.0.0.1:8121
        metaData:
          weight: 10
      - url: http://127.0.0.1:8122
        metaData:
          weight: 5
      - url: http://127.0.0.1:8123
        metaData:
          weight: 7
      - url: http://127.0.0.1:8124
        metaData:
          weight: 3
      - url: http://127.0.0.1:8125
        metaData:
          weight: 6
      - url: http://127.0.0.1:8126
        metaData:
          weight: 4
      - url: http://127.0.0.1:8127
        metaData:
          weight: 8
      - url: http://127.0.0.1:8128
        metaData:
          weight: 2
      - url: http://127.0.0.1:8129
        metaData:
          weight: 9
      - url: http://127.0.0.1:8130
        metaData:
          weight: 1
      - url: http://127.0.0.1:8131
        metaData:
          weight: 10
      - url: http://127.0.0.1:8132
        metaData:
          weight: 5
      - url: http://127.0.0.1:8133
        metaData:
          weight: 7
      - url: http://127.0.0.1:8134
        metaData:
          weight: 3
      - url: http://127.0.0.1:8135
        metaData:
          weight: 6
      - url: http://127.0.0.1:8136
        metaData:
          weight: 4
      - url: http://127.0.0.1:8137
        metaData:
          weight: 8
      - url: http://127.0.0.1:8138
        metaData:
          weight: 2
      - url: http://127.0.0.1:8139
        metaData:
          weight: 9
      - url: http://127.0.0.1:8140
        metaData:
          weight: 1
      - url: http://127.0.0.1:8141
        metaData:
          weight: 10
      - url: http://127.0.0.1:8142
        metaData:
          weight: 5
      - url: http://127.0.0.1:8143
        metaData:
          weight: 7
      - url: http://127.0.0.1:8144
        metaData:
          weight: 3
      - url: http://127.0.0.1:8145
        metaData:
          weight: 6
      - url: http://127.0.0.1:8146
        metaData:
          weight: 4
      - url: http://127.0.0.1:8147
        metaData:
          weight: 8
      - url: http://127.0.0.1:8148
        metaData:
          weight: 2
      - url: http://127.0.0.1:8149
        metaData:
          weight: 9
      - url: http://127.0.0.1:8150
        metaData:
          weight: 1

